apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/elysiansky/capstone-chart-kong-gateway.git'
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
